### ISSUE TITLE
It works with server side rendering?

### ISSUE THREAD

**Issue by cloud-walker** [mhaagens/lazy-route#1]
I'm investigating on this topic too, but my solution is not working on the server side

**Comment by cpeddecord** [comment]
it's only using `componentDidMount`, it won't load on the server.

**Comment by mhaagens** [comment]
Yeah, this doesn't work for server side rendering.
A possible enhancement would be to check for an environment variable such as BUILD_TARGET=server and then run require on the server, which is what I'm doing in my projects at the moment. I plan on making an SSR branch of this component, I'll let you know once it's ready for testing.
