### ISSUE TITLE
Can not use with Switch

### ISSUE THREAD

**Issue by yezongyang** [mhaagens/lazy-route#4]

**Comment by arvigeus** [comment]
Try this for now:
`<Route render={() => <LazyRoute component={import("myComponent")}>}/>`

**Comment by aldarund** [comment]
@arvigeus isnt it the same as in docs except there no props? I  tried same but with props and it doesnt work with switch

**Comment by pc035860** [comment]
@aldarund I just send a PR for the <Switch> support. You can try it on my branch before the PR gets merged.

**Comment by zanjs** [comment]
@pc035860  https://github.com/ReactTraining/react-router/issues/5411

Thinks you

**Comment by mlewis-sandow** [comment]
I ran into the same issue. That change resolved it. Thanks @pc035860
